import type { Lead } from "@/types";

/** Synthetic WhatsApp-first SMB lead seed (mirrors data/seed/whatsapp_leads_demo.csv). */
export const DEMO_LEADS: Lead[] = [
  {
    id: "L-001",
    name: "Ana Clínica Estética",
    channel: "whatsapp",
    stage: "qualified",
    owner: "Mariana",
    source: "instagram_dm",
    created_at: "2026-07-01T10:12:00",
    first_response_minutes: 18,
    last_touch_at: "2026-07-07T09:00:00",
    next_follow_up_at: "2026-07-09T11:00:00",
    opportunity_score: 86,
    estimated_revenue: 2400,
    temperature: "hot",
    lost_reason: null,
    notes: "Pediu orçamento de pacote facial e sumiu após áudio.",
    tags: ["hot", "follow-up"],
  },
  {
    id: "L-002",
    name: "Bruno Imóveis Centro",
    channel: "instagram",
    stage: "proposal",
    owner: "Carlos",
    source: "instagram_form",
    created_at: "2026-06-28T15:40:00",
    first_response_minutes: 42,
    last_touch_at: "2026-07-06T18:20:00",
    next_follow_up_at: "2026-07-08T16:00:00",
    opportunity_score: 78,
    estimated_revenue: 5200,
    temperature: "hot",
    lost_reason: null,
    notes: "Visitou 2 imóveis; aguarda contraproposta.",
    tags: ["proposal", "high-ticket"],
  },
  {
    id: "L-003",
    name: "Curso UX Intensivo",
    channel: "form",
    stage: "contacted",
    owner: "Mariana",
    source: "landing_form",
    created_at: "2026-07-05T08:05:00",
    first_response_minutes: 95,
    last_touch_at: "2026-07-05T09:40:00",
    next_follow_up_at: "2026-07-09T09:30:00",
    opportunity_score: 61,
    estimated_revenue: 997,
    temperature: "warm",
    lost_reason: null,
    notes: "Perguntou parcelamento e não respondeu.",
    tags: ["course", "slow-response"],
  },
  {
    id: "L-004",
    name: "Escola Bilíngue Norte",
    channel: "whatsapp",
    stage: "new",
    owner: "Carlos",
    source: "whatsapp_status",
    created_at: "2026-07-08T19:10:00",
    first_response_minutes: null,
    last_touch_at: "2026-07-08T19:10:00",
    next_follow_up_at: "2026-07-09T08:00:00",
    opportunity_score: 72,
    estimated_revenue: 3600,
    temperature: "hot",
    lost_reason: null,
    notes: "Lead novo sem primeira resposta.",
    tags: ["forgotten", "critical"],
  },
  {
    id: "L-005",
    name: "Studio Pilates Sul",
    channel: "whatsapp",
    stage: "lost",
    owner: "Mariana",
    source: "referral",
    created_at: "2026-06-20T11:00:00",
    first_response_minutes: 210,
    last_touch_at: "2026-06-27T14:00:00",
    next_follow_up_at: null,
    opportunity_score: 20,
    estimated_revenue: 1800,
    temperature: "cold",
    lost_reason: "demora_no_retorno",
    notes: "Fechou com concorrente após 3 dias sem follow-up.",
    tags: ["lost", "response-sla"],
  },
  {
    id: "L-006",
    name: "Clínica Odontológica Vida",
    channel: "instagram",
    stage: "qualified",
    owner: "Ana",
    source: "instagram_ads",
    created_at: "2026-07-02T13:22:00",
    first_response_minutes: 12,
    last_touch_at: "2026-07-08T10:15:00",
    next_follow_up_at: "2026-07-10T10:00:00",
    opportunity_score: 81,
    estimated_revenue: 4100,
    temperature: "hot",
    lost_reason: null,
    notes: "Quer agenda para avaliação esta semana.",
    tags: ["hot", "booking"],
  },
  {
    id: "L-007",
    name: "Agência Tráfego Local",
    channel: "form",
    stage: "proposal",
    owner: "Carlos",
    source: "agency_partner",
    created_at: "2026-06-30T09:00:00",
    first_response_minutes: 27,
    last_touch_at: "2026-07-07T17:45:00",
    next_follow_up_at: "2026-07-09T15:00:00",
    opportunity_score: 74,
    estimated_revenue: 8900,
    temperature: "warm",
    lost_reason: null,
    notes: "Multi-cliente: 4 negócios locais no pipeline.",
    tags: ["agency", "multi-client"],
  },
  {
    id: "L-008",
    name: "Loja Moda Outlet",
    channel: "whatsapp",
    stage: "contacted",
    owner: "Ana",
    source: "whatsapp_catalog",
    created_at: "2026-07-04T16:50:00",
    first_response_minutes: 65,
    last_touch_at: "2026-07-04T18:00:00",
    next_follow_up_at: "2026-07-09T12:00:00",
    opportunity_score: 48,
    estimated_revenue: 650,
    temperature: "warm",
    lost_reason: null,
    notes: "Pediu preço e sumiu.",
    tags: ["price-ask", "follow-up"],
  },
  {
    id: "L-009",
    name: "Consultoria Contábil PME",
    channel: "manual",
    stage: "won",
    owner: "Mariana",
    source: "manual_entry",
    created_at: "2026-06-15T10:00:00",
    first_response_minutes: 8,
    last_touch_at: "2026-06-25T11:00:00",
    next_follow_up_at: null,
    opportunity_score: 95,
    estimated_revenue: 3200,
    temperature: "hot",
    lost_reason: null,
    notes: "Fechou plano mensal após 2 follow-ups.",
    tags: ["won", "playbook"],
  },
  {
    id: "L-010",
    name: "Pet Shop Jardins",
    channel: "whatsapp",
    stage: "lost",
    owner: "Carlos",
    source: "instagram_dm",
    created_at: "2026-06-22T20:00:00",
    first_response_minutes: 340,
    last_touch_at: "2026-06-24T09:00:00",
    next_follow_up_at: null,
    opportunity_score: 15,
    estimated_revenue: 900,
    temperature: "cold",
    lost_reason: "preco",
    notes: "Achou caro após demora na resposta.",
    tags: ["lost", "price"],
  },
  {
    id: "L-011",
    name: "Academia Fit Night",
    channel: "instagram",
    stage: "new",
    owner: "Ana",
    source: "instagram_form",
    created_at: "2026-07-08T21:30:00",
    first_response_minutes: null,
    last_touch_at: "2026-07-08T21:30:00",
    next_follow_up_at: "2026-07-09T07:30:00",
    opportunity_score: 69,
    estimated_revenue: 1290,
    temperature: "warm",
    lost_reason: null,
    notes: "Formulário noturno sem atendimento.",
    tags: ["forgotten", "after-hours"],
  },
  {
    id: "L-012",
    name: "Salão Beauty Prime",
    channel: "whatsapp",
    stage: "qualified",
    owner: "Mariana",
    source: "referral",
    created_at: "2026-07-03T12:10:00",
    first_response_minutes: 22,
    last_touch_at: "2026-07-07T13:00:00",
    next_follow_up_at: "2026-07-09T14:00:00",
    opportunity_score: 77,
    estimated_revenue: 2100,
    temperature: "hot",
    lost_reason: null,
    notes: "Quer pacote mensal para equipe.",
    tags: ["hot", "b2b"],
  },
];

export const DEMO_NOTICE =
  "Lab demo com 12 leads sintéticos (WhatsApp/Instagram/formulário). KPIs e scores são do snapshot de demonstração — não métricas de produção.";
